import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/craft";
import { ThemeProvider } from "next-themes";
import { Background } from "@/components/custom/background";
import Navbar from "@/components/custom/navbar"; // Moved Navbar here

const font = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jishnu's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout className={font.className}>
      <body className="px-4 xl:px-0 overflow-x-hidden">
        <Background />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <div className="lg:w-[40%] md:w-[90%] m-auto">
            <Navbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </Layout>
  );
}
